config/routes.rb
Rails.application.routes.draw do
  root 'addictions#index'  
  post   '/like/:addiction_id' => 'likes#like',   as: 'like'
  delete '/like/:addiction_id' => 'likes#unlike', as: 'unlike'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'addictions/search', to: 'addictions#search', as: 'addictions_search'

  resources :stars, only: [:index, :show]
  resources :addictions, only: [:index, :show]
  resources :likes, only: [:index]
end

app/models/addiction.rb
class Addiction < ApplicationRecord
  belongs_to  :star,    optional: true

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  enum status: { job: 0, hobby: 1 }

  scope :job,    -> { where status: 0 }
  scope :hobby,  -> { where status: 1 }
  scope :rand10, -> { order("RAND()").limit(10) }
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/hometown.rb
class Hometown < ApplicationRecord
  has_many :stars
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :addiction, counter_cache: :likes_count
  belongs_to :user
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  has_many :stars
end

app/models/school_club.rb
class SchoolClub < ApplicationRecord
  has_many :stars
end

app/models/school_event.rb
class SchoolEvent < ApplicationRecord
  has_many :stars_like_events
  has_many :stars_dislike_events

  has_many :like_stars,    through: :stars_like_events,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_events, source: :stars
end

app/models/school_place.rb
class SchoolPlace < ApplicationRecord
  has_many :stars_like_places
  has_many :stars_dislike_places

  has_many :like_stars,    through: :stars_like_places,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_places, source: :stars
end

app/models/school_subject.rb
class SchoolSubject < ApplicationRecord
  has_many :stars_like_subjects
  has_many :stars_dislike_subjects

  has_many :like_stars,    through: :stars_like_subjects,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_subjects, source: :stars
end

app/models/speciality_tag.rb
class SpecialityTag < ApplicationRecord
  has_many :stars_speciality_tags
  has_many :stars, through: :stars_speciality_tags
end

app/models/star.rb
class Star < ApplicationRecord
  # TODO:boolean型はfalse=0、true=1の整合性を保存時に担保する
  enum gender:                { male: 0, female: 1, other: 2 }
  enum sibling_position:      { the_only: 0, the_eldest: 1, the_second: 2, the_third: 3, the_fourth: 4, the_youngest: 5}
  enum family_env:            { ordinary: 0, fatherless: 1, motherless: 2, foster_parents: 3 }
  enum economic_situation:    { rich: 0, normal: 1, poor: 2 }
  enum preference_for_school: { love: 0, like: 1, soso: 2, dislike: 3, hate: 4 }
  enum truancy_experience: { true: true, false: false }

  belongs_to              :occupation,   optional: true
  belongs_to              :hometown,     optional: true
  belongs_to              :school_club,  optional: true
  has_one                 :addiction,    dependent: :destroy

  has_many :stars_like_places,      dependent: :destroy
  has_many :like_places,           through: :stars_like_places
  has_many :stars_dislike_places,   dependent: :destroy
  has_many :dislike_places,        through: :stars_dislike_places

  has_many :stars_like_events,      dependent: :destroy
  has_many :like_events,            through: :stars_like_events
  has_many :stars_dislike_events,   dependent: :destroy
  has_many :dislike_events,         through: :stars_dislike_events
  has_many :stars_like_subjects,    dependent: :destroy
  has_many :like_subjects,          through: :stars_like_subjects
  has_many :stars_dislike_subjects, dependent: :destroy
  has_many :dislike_subjects,      through: :stars_dislike_subjects
  has_many :stars_lessons, dependent: :destroy
  has_many :lessons,           through: :stars_lessons

  has_many :stars_speciality_tags, dependent: :destroy
  has_many :speciality_tags, through: :stars_speciality_tags
  has_many :stars_worry_tags, dependent: :destroy
  has_many :worry_tags, through: :stars_worry_tags

  accepts_nested_attributes_for :like_events

  def self.enums_i18n_ransack(enum_name)
    enums = eval("self.#{enum_name.to_s.pluralize}")
    enums.map { |k, v| [eval("self.#{enum_name.to_s.pluralize}_i18n")[k], v] }
  end
end

app/models/star_like_event.rb
class StarLikeEvent < ApplicationRecord
  belongs_to :school_event
  belongs_to :star
end

app/models/star_like_place.rb
class StarLikePlace < ApplicationRecord
  belongs_to :school_place
  belongs_to :star
end

app/models/star_like_subject.rb
class StarLikeSubject < ApplicationRecord
  belongs_to :school_subject
  belongs_to :star
end

app/models/stars_like_event.rb
class StarsLikeEvent < ApplicationRecord
  belongs_to :like_event, class_name: "SchoolEvent", foreign_key:"school_event_id"
  belongs_to :star
end

app/models/stars_like_place.rb
class StarsLikePlace < ApplicationRecord
  belongs_to :like_place, class_name: "SchoolPlace", foreign_key:"school_place_id"
  belongs_to :star
end

app/models/stars_worry_tag.rb
class StarsWorryTag < ApplicationRecord
  belongs_to :worry_tag
  belongs_to :star
end

app/models/strength_tag.rb
class StrengthTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes,      dependent: :destroy
  has_many :addictions, through: :likes
end

app/models/weakness_tag.rb
class WeaknessTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/worry_tag.rb
class WorryTag < ApplicationRecord

has_many :stars_worry_tags
has_many :stars, through: :stars_worry_tags

end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_action :set_star, only: [:show]

  # GET /stars
  # GET /stars.json
  def index
    respond_to do |format|
      format.json {
        case params[:category]
        when "speciality"
          @tags = SpecialityTag.where( 'name Like(?)',"%#{params[:keyword]}%" )
        when "worry"
          @tags = WorryTag.where( 'name Like(?)',"%#{params[:keyword]}%" )
        end
      }
    end
  end

  # GET /stars/1
  # GET /stars/1.json
  def show
  end

  # # GET /stars/new
  # def new
  #   @star = Star.new
  # end

  # # GET /stars/1/edit
  # def edit
  # end

  # # POST /stars
  # # POST /stars.json
  # def create
  #   @star = Star.new(star_params)

  #   respond_to do |format|
  #     if @star.save
  #       format.html { redirect_to @star, notice: 'Star was successfully created.' }
  #       format.json { render :show, status: :created, location: @star }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @star.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /stars/1
  # # PATCH/PUT /stars/1.json
  # def update
  #   respond_to do |format|
  #     if @star.update(star_params)
  #       format.html { redirect_to @star, notice: 'Star was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @star }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @star.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /stars/1
  # # DELETE /stars/1.json
  # def destroy
  #   @star.destroy
  #   respond_to do |format|
  #     format.html { redirect_to stars_url, notice: 'Star was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_star
      @star = Star.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def star_params
      params.fetch(:star, {})
    end
end

app/views/stars/_check_boxes_for_enum.html.haml
%tr#search_condition_item_row_lodger.sortable_row
  %th
    =table_row_name(enum)
    %p.note 複数可
  %td
    %ul.form_list
      %li.form_item.do_not_care
        =check_box_tag "q[#{enum}_in][]", "", checked: true
        %label.for_items.do_not_care
          こだわらない
      -Star.enums_i18n_ransack(:"#{enum}").each do |ele|
        %li.form_item
          =check_box_tag "q[#{enum}_in][]", ele[1], false
          %label.for_items
            =ele[0]

app/views/stars/_search_form.html.haml
#user-modal.modal.fade{tabindex:"-1", role:"dialog", aria:{hidden:"true"}}
  .modal-dialog
    #modal_search_condition.modal-content
      .box_search_form
        %ul.search_tab_menu
          %li.tab_menu_item.is_current.w100p
            %a あなたの希望条件
        = search_form_for q, url:stars_path, html:{id: 'search_condition_form'} do |f|
          .search_form_inner
            %table#search_condition_table.box_user_detail
              %tbody
                %tr
                  %th 年齢
                  %td#search-age.search_age
                    =f.select :birthday_to_age_gteq, options_for_select((18..65).map{|n| ["#{n}", n]}),{include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                    %span 〜
                    =f.select :birthday_to_age_lteq, options_for_select((18..65).map{|n| ["#{n}", n]}), {include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "hometown" }
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "school_club" }
                = render partial:"form_for_tags", locals: { category: "speciality" }
                = render partial:"form_for_tags", locals: { category: "worry" }
                = render partial:"check_boxes_for_enum", locals: { enum: "gender" }
                = render partial:"check_boxes_for_enum", locals: { enum: "sibling_position" }
                = render partial:"check_boxes_for_enum", locals: { enum: "family_env" }
                = render partial:"check_boxes_for_enum", locals: { enum: "economic_situation" }
                = render partial:"check_boxes_for_enum", locals: { enum: "preference_for_school" }
                = render partial:"check_boxes_for_enum", locals: { enum: "truancy_experience" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_event", junction_table: "stars_like_event" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_event", junction_table: "stars_dislike_event" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_subject", junction_table: "stars_like_subject" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_subject", junction_table: "stars_dislike_subject" }
            %ul.box_serach_button
              %li.serach_button_item.w20p
                %button#cancelSearchConditionBtn.modal-close.button_a.button_white_a{type:"button", data:{dismiss:"modal"}} キャンセル
              %li.serach_button_item.w40p
                %button#submitSearchConditionBtn.button_a.button_blue_a{type: "submit",remote:true} この条件で検索する

app/views/stars/_stars.html.erb
<%= render 'likes/like', star: star %>

app/views/stars/index.html.erb
なんでやねん
abcde
<div class="c-card__mediaAction">
  <span class="c-card__mediaActionButton c-card__mediaActionButton--favorite js-favorite  is-active" data-product-id="14242833" data-active="false">お気に入り(minneからの引用)</span>
</div>
  <%= link_to "idが１の人", star_path(@stars.ids[0])%><br>
  <%= link_to "idが2の人", star_path(@stars.ids[1])%><br><br><br>

<%= render 'shared/header' %>
<%= render 'shared/search_head' %>
<%= render 'shared/addiction_card' %>
<%= render partial: 'shared/user_search_form', locals: { q: @q } %>



<!-- もし現在のユーザーがいいね!ボタンを押したら、表示する。
else,押さなかったら表示しない,みたいにしたい。今のままだと、
likes_countが１以上だと表示されちゃう。 -->

app/views/stars/like_detail.html.erb
お気に入り(自分がハートマークをつけたもの)のページ<br>
<br><br><br>
<% @starss.each do |star| %>
  <div class="sample">
  <% if star.likes_count >= 1 %>
  <%= link_to star.name, star_path(star.id)%>さんのページへ
  <% else %>
  <% end %>
</div>
<% end %>

app/views/stars/show.html.erb
%p#notice= notice
たちつてと

<%= image_tag(@star.avatar)%>
<div class = "qqq" ><%= @star.name %></div>
<%= render partial: 'likes/like', locals: {star: @star} %>