config/routes.rb
Rails.application.routes.draw do
  root 'addictions#index'  
  post   '/like/:addiction_id' => 'likes#like',   as: 'like'
  delete '/like/:addiction_id' => 'likes#unlike', as: 'unlike'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'addictions/search', to: 'addictions#search', as: 'addictions_search'

  resources :stars, only: [:index, :show]
  resources :addictions, only: [:index, :show]
  resources :likes, only: [:index]
end

app/models/addiction.rb
class Addiction < ApplicationRecord
  belongs_to  :star,    optional: true

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  enum status: { job: 0, hobby: 1 }

  scope :job,    -> { where status: 0 }
  scope :hobby,  -> { where status: 1 }
  scope :rand10, -> { order("RAND()").limit(10) }
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/hometown.rb
class Hometown < ApplicationRecord
  has_many :stars
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :addiction, counter_cache: :likes_count
  belongs_to :user
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  has_many :stars
end

app/models/school_club.rb
class SchoolClub < ApplicationRecord
  has_many :stars
end

app/models/school_event.rb
class SchoolEvent < ApplicationRecord
  has_many :stars_like_events
  has_many :stars_dislike_events

  has_many :like_stars,    through: :stars_like_events,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_events, source: :stars
end

app/models/school_place.rb
class SchoolPlace < ApplicationRecord
  has_many :stars_like_places
  has_many :stars_dislike_places

  has_many :like_stars,    through: :stars_like_places,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_places, source: :stars
end

app/models/school_subject.rb
class SchoolSubject < ApplicationRecord
  has_many :stars_like_subjects
  has_many :stars_dislike_subjects

  has_many :like_stars,    through: :stars_like_subjects,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_subjects, source: :stars
end

app/models/speciality_tag.rb
class SpecialityTag < ApplicationRecord
  has_many :stars_speciality_tags
  has_many :stars, through: :stars_speciality_tags
end

app/models/star.rb
class Star < ApplicationRecord
  # TODO:boolean型はfalse=0、true=1の整合性を保存時に担保する
  enum gender:                { male: 0, female: 1, other: 2 }
  enum sibling_position:      { the_only: 0, the_eldest: 1, the_second: 2, the_third: 3, the_fourth: 4, the_youngest: 5}
  enum family_env:            { ordinary: 0, fatherless: 1, motherless: 2, foster_parents: 3 }
  enum economic_situation:    { rich: 0, normal: 1, poor: 2 }
  enum preference_for_school: { love: 0, like: 1, soso: 2, dislike: 3, hate: 4 }
  enum truancy_experience: { true: true, false: false }

  belongs_to              :occupation,   optional: true
  belongs_to              :hometown,     optional: true
  belongs_to              :school_club,  optional: true
  has_one                 :addiction,    dependent: :destroy

  has_many :stars_like_places,      dependent: :destroy
  has_many :like_places,           through: :stars_like_places
  has_many :stars_dislike_places,   dependent: :destroy
  has_many :dislike_places,        through: :stars_dislike_places

  has_many :stars_like_events,      dependent: :destroy
  has_many :like_events,            through: :stars_like_events
  has_many :stars_dislike_events,   dependent: :destroy
  has_many :dislike_events,         through: :stars_dislike_events
  has_many :stars_like_subjects,    dependent: :destroy
  has_many :like_subjects,          through: :stars_like_subjects
  has_many :stars_dislike_subjects, dependent: :destroy
  has_many :dislike_subjects,      through: :stars_dislike_subjects
  has_many :stars_lessons, dependent: :destroy
  has_many :lessons,           through: :stars_lessons

  has_many :stars_speciality_tags, dependent: :destroy
  has_many :speciality_tags, through: :stars_speciality_tags
  has_many :stars_worry_tags, dependent: :destroy
  has_many :worry_tags, through: :stars_worry_tags

  accepts_nested_attributes_for :like_events

  def self.enums_i18n_ransack(enum_name)
    enums = eval("self.#{enum_name.to_s.pluralize}")
    enums.map { |k, v| [eval("self.#{enum_name.to_s.pluralize}_i18n")[k], v] }
  end
end

app/models/star_like_event.rb
class StarLikeEvent < ApplicationRecord
  belongs_to :school_event
  belongs_to :star
end

app/models/star_like_place.rb
class StarLikePlace < ApplicationRecord
  belongs_to :school_place
  belongs_to :star
end

app/models/star_like_subject.rb
class StarLikeSubject < ApplicationRecord
  belongs_to :school_subject
  belongs_to :star
end

app/models/stars_like_event.rb
class StarsLikeEvent < ApplicationRecord
  belongs_to :like_event, class_name: "SchoolEvent", foreign_key:"school_event_id"
  belongs_to :star
end

app/models/stars_like_place.rb
class StarsLikePlace < ApplicationRecord
  belongs_to :like_place, class_name: "SchoolPlace", foreign_key:"school_place_id"
  belongs_to :star
end

app/models/stars_worry_tag.rb
class StarsWorryTag < ApplicationRecord
  belongs_to :worry_tag
  belongs_to :star
end

app/models/strength_tag.rb
class StrengthTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes,      dependent: :destroy
  has_many :addictions, through: :likes
end

app/models/weakness_tag.rb
class WeaknessTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/worry_tag.rb
class WorryTag < ApplicationRecord

has_many :stars_worry_tags
has_many :stars, through: :stars_worry_tags

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_variables, only: [:like, :unlike]

  def index
    @addictions = current_user.addictions
  end

  def like
    like = current_user.likes.new(addiction_id: @addiction.id)
    like.save
  end

  def unlike
    like = current_user.likes.find_by(addiction_id: @addiction.id)
    like.destroy
  end

  private

  def set_variables
    @addiction = Addiction.find(params[:addiction_id])
    @id_name = "#like-button-#{@addiction.id}"
  end

end

app/views/likes/_like.html.haml
.favorite-btn{:id => "like-button-#{addiction.id}"}
  - if current_user.likes.find_by(addiction_id: addiction.id)
    = link_to unlike_path(addiction.id), method: :delete, remote: true do
      .favorite-btn__star
        %p ⭐
  - else
    = link_to like_path(addiction.id), method: :post, remote: true do
      .favorite-btn__star
        %p ★

app/views/likes/index.html.haml
= render 'shared/header'
= render 'shared/head_jumbotron'
%br/
%br/
#like__detail-container
  .galleryHeader
    .galleryHeader__title
      = current_user.name
      GALLERY
  .c-tabNav
    %ul.c-tabNav__list
      %li.c-tabNav__item
        お気に入り
  %h2
    = current_user.name
    さんのお気に入りの未来像
  .album.py-5.bg-light.container
    .row
      - @addictions.each do |addiction|
        .col-lg-4.col-sm-6
          .addiction-card.card.mx-1.my-1
            = link_to(addiction_path(addiction.id), class: 'profile__card') do
              .card-main-image.box-shadow
                = image_tag(addiction.image)
              .card-body.p-3
                .card-left.col-md-3.p-0
                  .rounded-circle.image-icon
                    = image_tag(addiction.star.avatar,class: "")
                .card-right.col-md-9.p-0
                  .card-text.pl-2
                    %h4.addiction_title{style:"-webkit-box-orient: vertical;"}
                      = addiction.title
                    %p{style:"-webkit-box-orient: vertical;"}= addiction.summary

app/views/likes/like.js.haml
$(".favorite").html('#{escape_javascript(render("likes/like", addiction: @addiction  ))}');

app/views/likes/unlike.js.haml
$(".favorite").html('#{escape_javascript(render("likes/like", addiction: @addiction  ))}');