config/routes.rb
Rails.application.routes.draw do
  root 'addictions#index'  
  post   '/like/:addiction_id' => 'likes#like',   as: 'like'
  delete '/like/:addiction_id' => 'likes#unlike', as: 'unlike'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'addictions/search', to: 'addictions#search', as: 'addictions_search'

  resources :stars, only: [:index, :show]
  resources :addictions, only: [:index, :show]
  resources :likes, only: [:index]
end

app/models/addiction.rb
class Addiction < ApplicationRecord
  belongs_to  :star,    optional: true

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  enum status: { job: 0, hobby: 1 }

  scope :job,    -> { where status: 0 }
  scope :hobby,  -> { where status: 1 }
  scope :rand10, -> { order("RAND()").limit(10) }
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/hometown.rb
class Hometown < ApplicationRecord
  has_many :stars
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :addiction, counter_cache: :likes_count
  belongs_to :user
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  has_many :stars
end

app/models/school_club.rb
class SchoolClub < ApplicationRecord
  has_many :stars
end

app/models/school_event.rb
class SchoolEvent < ApplicationRecord
  has_many :stars_like_events
  has_many :stars_dislike_events

  has_many :like_stars,    through: :stars_like_events,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_events, source: :stars
end

app/models/school_place.rb
class SchoolPlace < ApplicationRecord
  has_many :stars_like_places
  has_many :stars_dislike_places

  has_many :like_stars,    through: :stars_like_places,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_places, source: :stars
end

app/models/school_subject.rb
class SchoolSubject < ApplicationRecord
  has_many :stars_like_subjects
  has_many :stars_dislike_subjects

  has_many :like_stars,    through: :stars_like_subjects,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_subjects, source: :stars
end

app/models/speciality_tag.rb
class SpecialityTag < ApplicationRecord
  has_many :stars_speciality_tags
  has_many :stars, through: :stars_speciality_tags
end

app/models/star.rb
class Star < ApplicationRecord
  # TODO:boolean型はfalse=0、true=1の整合性を保存時に担保する
  enum gender:                { male: 0, female: 1, other: 2 }
  enum sibling_position:      { the_only: 0, the_eldest: 1, the_second: 2, the_third: 3, the_fourth: 4, the_youngest: 5}
  enum family_env:            { ordinary: 0, fatherless: 1, motherless: 2, foster_parents: 3 }
  enum economic_situation:    { rich: 0, normal: 1, poor: 2 }
  enum preference_for_school: { love: 0, like: 1, soso: 2, dislike: 3, hate: 4 }
  enum truancy_experience: { true: true, false: false }

  belongs_to              :occupation,   optional: true
  belongs_to              :hometown,     optional: true
  belongs_to              :school_club,  optional: true
  has_one                 :addiction,    dependent: :destroy

  has_many :stars_like_places,      dependent: :destroy
  has_many :like_places,           through: :stars_like_places
  has_many :stars_dislike_places,   dependent: :destroy
  has_many :dislike_places,        through: :stars_dislike_places

  has_many :stars_like_events,      dependent: :destroy
  has_many :like_events,            through: :stars_like_events
  has_many :stars_dislike_events,   dependent: :destroy
  has_many :dislike_events,         through: :stars_dislike_events
  has_many :stars_like_subjects,    dependent: :destroy
  has_many :like_subjects,          through: :stars_like_subjects
  has_many :stars_dislike_subjects, dependent: :destroy
  has_many :dislike_subjects,      through: :stars_dislike_subjects
  has_many :stars_lessons, dependent: :destroy
  has_many :lessons,           through: :stars_lessons

  has_many :stars_speciality_tags, dependent: :destroy
  has_many :speciality_tags, through: :stars_speciality_tags
  has_many :stars_worry_tags, dependent: :destroy
  has_many :worry_tags, through: :stars_worry_tags

  accepts_nested_attributes_for :like_events

  def self.enums_i18n_ransack(enum_name)
    enums = eval("self.#{enum_name.to_s.pluralize}")
    enums.map { |k, v| [eval("self.#{enum_name.to_s.pluralize}_i18n")[k], v] }
  end
end

app/models/star_like_event.rb
class StarLikeEvent < ApplicationRecord
  belongs_to :school_event
  belongs_to :star
end

app/models/star_like_place.rb
class StarLikePlace < ApplicationRecord
  belongs_to :school_place
  belongs_to :star
end

app/models/stars_like_event.rb
class StarsLikeEvent < ApplicationRecord
  belongs_to :like_event, class_name: "SchoolEvent", foreign_key:"school_event_id"
  belongs_to :star
end

app/models/stars_like_place.rb
class StarsLikePlace < ApplicationRecord
  belongs_to :like_place, class_name: "SchoolPlace", foreign_key:"school_place_id"
  belongs_to :star
end

app/models/stars_worry_tag.rb
class StarsWorryTag < ApplicationRecord
  belongs_to :worry_tag
  belongs_to :star
end

app/models/strength_tag.rb
class StrengthTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes,      dependent: :destroy
  has_many :addictions, through: :likes
end

app/models/weakness_tag.rb
class WeaknessTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/worry_tag.rb
class WorryTag < ApplicationRecord

has_many :stars_worry_tags
has_many :stars, through: :stars_worry_tags

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %meta{name: "viewport", content:"width=device-width, initial-scale=1"}
    %title BigC
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .contents
      = yield
    = render "shared/footer"

app/views/shared/_addiction_card.html.haml
.album.bg-light
  .container
    .row
      .scroll-contents.clearfix
        %ul
          - addictions.each do |addiction|
            %li.item.addiction-card.px-1.py-2.card
              = link_to addiction_path(addiction) do
                .card-main-image.box-shadow
                  = image_tag(addiction.image)
                .card-body.p-3
                  .card-left.col-md-3.p-0
                    .rounded-circle.image-icon
                      = image_tag(addiction.star.avatar, class: "")
                  .card-right.col-md-9.p-0
                    .card-text.pl-2
                      %h4.addiction_title{style:"-webkit-box-orient: vertical;"} #{addiction.title}
                      %p{style:"-webkit-box-orient: vertical;"}=addiction.summary

app/views/shared/_footer.html.haml
.container
  %footer.page-footer.font-small.pt-4
    .container-fluid.text-center.text-md-left
      .row
        .col-md-6.mt-md-0.mt-3
          %h5.text-uppercase お問い合わせ
          %p motoki_tabata@gmail.com
        %hr.clearfix.w-100.d-md-none.pb-3/
        .col-md-3.mb-md-0.mb-3
          %h5.text-uppercase 夢中になれる仕事を見つける
          %ul.list-unstyled
            %li
              = link_to "エ", "#"
            %li
              = link_to "ン", "#"
            %li
              = link_to "ジ", "#"
            %li
              = link_to "ニ", "#"
            %li
              = link_to "ア", "#"
        .col-md-3.mb-md-0.mb-3
          %h5.text-uppercase 夢中になれる趣味を見つける
          %ul.list-unstyled
            %li
              = link_to "プ", "#"
            %li
              = link_to "ロ", "#"
            %li
              = link_to "グ", "#"
            %li
              = link_to "ラ", "#"
            %li
              = link_to "ミ", "#"
            %li
              = link_to "ン", "#"
            %li
              = link_to "グ", "#"
    .footer-copyright.text-center.py-3
      © 2018 Copyright - 
      %a{href: "http://big-c.herokuapp.com/"} bigc.com

app/views/shared/_head_jumbotron.html.haml
= link_to root_path do
  .jumbotron.jumbotron-fluid
    .container.pt-xs-3.pt-lg-3
      %h1.display-4 mikke!
      %p.lead 未来の自分を探そう！

app/views/shared/_header.html.haml
%nav.navbar.p-0.mt-2
  %input#openSearchConditionBtn.form-control.col-lg-4.ml-4.mr-4{"aria-label" => "Search", placeholder: "Search", type: "text"}/
  %ul.navbar.nav
    %li.nav-item.text-nowrap.navbar-nav.pl-3.pr-3
      %a.nav-link{href: "#"} 閲覧履歴
    %li.nav-item.text-nowrap.navbar-nav.pl-3.pr-3
      = link_to "お気に入り", likes_path, class: "nav-link"
    - if user_signed_in?
      %li.nav-item.text-nowrap.navbar-nav.pl-3.pr-3
        = link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }

app/views/shared/_middle_jumbotron.html.haml
.description_background
  .container.pt-xs-3.pt-lg-3.mt-5.mb-5
    .row.justify-content-end.introduction.pb-0
      .col-lg-5
        .subtitle
          %h2 今の自分から探す、未来の自分
      .col-lg-7.align-self-end.box-like-cloth
        .description.mt-3
          .description__text
            %p ここは、あなたが夢中になれるものをみつける場所です。
            %p 自分と似た人、同じような特技や悩みを持った人たちが、
            %p いまどんなことに夢中になっているのか見てみましょう！

app/views/shared/_navbar.html.haml
= render partial: 'search_form', locals: { q: @q }
.fixed-header{style: "position: sticky; top: 0px; z-index: 5"}
  .fixed-header__wrapper
    .fixed-header__left
      = link_to root_path do
        = image_tag("starfish.jpeg", class: "header-icon", size: "30x30")
      %i.fa.fa-search.fa-lg#openSearchConditionBtn
    %ul.fixed-header__right
      %li.nav-item
        %a{href: "#"} 閲覧履歴
      %li.nav-item
        = link_to "お気に入り",likes_path
      - if user_signed_in?
        %li.nav-item
          = link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" }

    #header_show.clearfix
      %ul.navibar
        %li.item
          %a{href: "#profile", class: "scroll"} どんな人
        %li.item
          %a{href: "#summary", class: "scroll"} 夢中なこと
        %li.item
          %a{href: "#addicted-points", class: "scroll"} 楽しいところ
        %li.item
          %a{href: "#difficult-points", class: "scroll"} 大変なところ
        %li.item
          %a{href: "#trigger", class: "scroll"} ハマったきっかけ
        %li.item
          %a{href: "#future-aim", class: "scroll"} 将来の目標
        %li.item
          %a{href: "#trying-things", class: "scroll"} 日々取り組んでいること
        %li.item
          %a{href: "#message", class: "scroll"} メッセージ

app/views/shared/_search_head.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light{style: "position: sticky; top: 0px; z-index: 5"}
  %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", type: "button"}
    さがす
  #navbarNavDropdown.collapse.navbar-collapse{style: "position: sticky; top: 0px; z-index: 5"}
    %ul.navbar-nav
      %li.nav-item.active.pl-xs-3.pl-lg-3
        %a.nav-link.disabled 何から探す？
      %li.nav-item
        %a.nav-link#searchByPositive 好き・得意なこと
      %li.nav-item
        %a.nav-link#searchByNegative 嫌い・苦手なこと
      %li.nav-item
        %a.nav-link#searchByWorry 悩んでいること
      %li.nav-item
        %a.nav-link#searchByAll いろいろ