config/routes.rb
Rails.application.routes.draw do
  root 'addictions#index'  
  post   '/like/:addiction_id' => 'likes#like',   as: 'like'
  delete '/like/:addiction_id' => 'likes#unlike', as: 'unlike'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'addictions/search', to: 'addictions#search', as: 'addictions_search'

  resources :stars, only: [:index, :show]
  resources :addictions, only: [:index, :show]
  resources :likes, only: [:index]
end

app/models/addiction.rb
class Addiction < ApplicationRecord
  belongs_to  :star,    optional: true

  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  enum status: { job: 0, hobby: 1 }

  scope :job,    -> { where status: 0 }
  scope :hobby,  -> { where status: 1 }
  scope :rand10, -> { order("RAND()").limit(10) }
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/hometown.rb
class Hometown < ApplicationRecord
  has_many :stars
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :addiction, counter_cache: :likes_count
  belongs_to :user
end

app/models/occupation.rb
class Occupation < ApplicationRecord
  has_many :stars
end

app/models/school_club.rb
class SchoolClub < ApplicationRecord
  has_many :stars
end

app/models/school_event.rb
class SchoolEvent < ApplicationRecord
  has_many :stars_like_events
  has_many :stars_dislike_events

  has_many :like_stars,    through: :stars_like_events,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_events, source: :stars
end

app/models/school_place.rb
class SchoolPlace < ApplicationRecord
  has_many :stars_like_places
  has_many :stars_dislike_places

  has_many :like_stars,    through: :stars_like_places,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_places, source: :stars
end

app/models/school_subject.rb
class SchoolSubject < ApplicationRecord
  has_many :stars_like_subjects
  has_many :stars_dislike_subjects

  has_many :like_stars,    through: :stars_like_subjects,    source: :stars
  has_many :dislike_stars, through: :stars_dislike_subjects, source: :stars
end

app/models/speciality_tag.rb
class SpecialityTag < ApplicationRecord
  has_many :stars_speciality_tags
  has_many :stars, through: :stars_speciality_tags
end

app/models/star.rb
class Star < ApplicationRecord
  # TODO:boolean型はfalse=0、true=1の整合性を保存時に担保する
  enum gender:                { male: 0, female: 1, other: 2 }
  enum sibling_position:      { the_only: 0, the_eldest: 1, the_second: 2, the_third: 3, the_fourth: 4, the_youngest: 5}
  enum family_env:            { ordinary: 0, fatherless: 1, motherless: 2, foster_parents: 3 }
  enum economic_situation:    { rich: 0, normal: 1, poor: 2 }
  enum preference_for_school: { love: 0, like: 1, soso: 2, dislike: 3, hate: 4 }
  enum truancy_experience: { true: true, false: false }

  belongs_to              :occupation,   optional: true
  belongs_to              :hometown,     optional: true
  belongs_to              :school_club,  optional: true
  has_one                 :addiction,    dependent: :destroy

  has_many :stars_like_places,      dependent: :destroy
  has_many :like_places,           through: :stars_like_places
  has_many :stars_dislike_places,   dependent: :destroy
  has_many :dislike_places,        through: :stars_dislike_places

  has_many :stars_like_events,      dependent: :destroy
  has_many :like_events,            through: :stars_like_events
  has_many :stars_dislike_events,   dependent: :destroy
  has_many :dislike_events,         through: :stars_dislike_events
  has_many :stars_like_subjects,    dependent: :destroy
  has_many :like_subjects,          through: :stars_like_subjects
  has_many :stars_dislike_subjects, dependent: :destroy
  has_many :dislike_subjects,      through: :stars_dislike_subjects
  has_many :stars_lessons, dependent: :destroy
  has_many :lessons,           through: :stars_lessons

  has_many :stars_speciality_tags, dependent: :destroy
  has_many :speciality_tags, through: :stars_speciality_tags
  has_many :stars_worry_tags, dependent: :destroy
  has_many :worry_tags, through: :stars_worry_tags

  accepts_nested_attributes_for :like_events

  def self.enums_i18n_ransack(enum_name)
    enums = eval("self.#{enum_name.to_s.pluralize}")
    enums.map { |k, v| [eval("self.#{enum_name.to_s.pluralize}_i18n")[k], v] }
  end
end

app/models/star_like_event.rb
class StarLikeEvent < ApplicationRecord
  belongs_to :school_event
  belongs_to :star
end

app/models/star_like_place.rb
class StarLikePlace < ApplicationRecord
  belongs_to :school_place
  belongs_to :star
end

app/models/star_like_subject.rb
class StarLikeSubject < ApplicationRecord
  belongs_to :school_subject
  belongs_to :star
end

app/models/stars_like_event.rb
class StarsLikeEvent < ApplicationRecord
  belongs_to :like_event, class_name: "SchoolEvent", foreign_key:"school_event_id"
  belongs_to :star
end

app/models/stars_like_place.rb
class StarsLikePlace < ApplicationRecord
  belongs_to :like_place, class_name: "SchoolPlace", foreign_key:"school_place_id"
  belongs_to :star
end

app/models/stars_worry_tag.rb
class StarsWorryTag < ApplicationRecord
  belongs_to :worry_tag
  belongs_to :star
end

app/models/strength_tag.rb
class StrengthTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes,      dependent: :destroy
  has_many :addictions, through: :likes
end

app/models/weakness_tag.rb
class WeaknessTag < ApplicationRecord
  has_and_belongs_to_many :stars, optional: true
end

app/models/worry_tag.rb
class WorryTag < ApplicationRecord

has_many :stars_worry_tags
has_many :stars, through: :stars_worry_tags

end

app/controllers/addictions_controller.rb
class AddictionsController < ApplicationController
  before_action :set_addiction, only: :show
  before_action :set_ransack_q,  only: [:index, :show, :search]

  def index
    @addictions_job     = Addiction.job.rand10.includes(:star)
    @addictions_hobby   = Addiction.hobby.rand10.includes(:star)
    @addictions_browsed = Addiction.rand10.includes(:star)
  end

  def show
    @star = @addiction.star
  end
  
  def search
  end

  private
  def set_addiction
    @addiction = Addiction.find(params[:id])
  end

  def set_ransack_q
    @q     = Star.ransack(params[:q])
    @stars = @q.result(distinct: true)
  end
end

app/views/addictions/_addictions.html.haml
= render 'likes/like', addiction: addiction

app/views/addictions/_check_boxes_for_enum.html.haml
%tr#search_condition_item_row_lodger.sortable_row
  %th
    =translate_to_japanese(enum)
    %p.note 複数可
  %td
    %ul.form_list
      -Star.enums_i18n_ransack(:"#{enum}").each do |ele|
        %li.form_item
          =check_box_tag "q[#{enum}_in][]", ele[1], false
          %label.for_items
            =ele[0]

app/views/addictions/_form.html.haml
/ = form_for @star do |f|
/   - if @star.errors.any?
/     #error_explanation
/       %h2= "#{pluralize(@star.errors.count, "error")} prohibited this star from being saved:"
/       %ul
/         - @star.errors.full_messages.each do |message|
/           %li= message

/   .actions
/     = f.submit 'Save'

app/views/addictions/_form_for_tags.html.haml
%tr#search_condition_item_row_residence.search_condition
  %th
    =translate_to_japanese(row_name)
  %td#residence.search_residence
    .form_block.nocustom
      %input.form-control{class:"#{category}-tag-search-field",type:"text", placeholder: "入力してください", data:{category: category}}
    %ul{id:"#{category}-tag-list"}
    .pt-2{id:"#{category}-search-result"}

app/views/addictions/_profile_card.html.haml
.profile-card.pb-4.clearfix
  .card-top.col-lg-3
    .rounded-circle.image-icon
      = image_tag("#{@star.avatar}", class: "")
    .card-title
      %span=@star.name
    .card-title
      %span ( #{@star.occupation.name} )

  .card-bottom.col-xs-10.col-lg-9
    %a{"data-toggle" => "collapse", :href => "#collapse1", class: "seemore"}
      %ul.profile-list
        %li.basic-info
          %h4.mb-1 基本情報
          .list-contents
            .list-contents__left
              %p 生年月日：#{@star.birthday}
              %p 出身地　：#{@star.hometown.name}
              %p 兄弟姉妹：#{@star.sibling_position_i18n}
            .list-contents__right
              %p 家庭環境：#{@star.family_env_i18n}
              %p 経済状況：#{@star.economic_situation_i18n}
              %p 不登校　：経験#{@star.truancy_experience_i18n}
        %li
          %h5.mb-1 好きなこと・特技
          .list-contents
            - @star.speciality_tags.each do |speciality|
              %span.tag ##{speciality.name}
        %li
          %h5.mb-1 苦手なこと・悩み
          .list-contents
            - @star.worry_tags.each do |worry|
              %span.tag ##{worry.name}
    .panel-group
      .panel.panel-default
        #collapse1.panel-collapse.collapse
          %a{"data-toggle" => "collapse", :href => "#collapse1", class: "seemore"}
            %ul.profile-list.panel-body
              %li
                %h5.mb-1 学生時代の部活動
                .list-contents
                  %span.item #{@star.school_club.name}
              %li
                %h5.mb-1 好きだった教科
                .list-contents
                  - @star.like_subjects.each do |subject|
                    %span.item #{subject.name}
              %li
                %h5.mb-1 苦手だった教科
                .list-contents
                  - @star.dislike_subjects.each do |subject|
                    %span.item #{subject.name}
              %li
                %h5.mb-1 好きだった学校行事
                .list-contents
                  - @star.like_events.each do |event|
                    %span.item #{event.name}
              %li
                %h5.mb-1 苦手だった学校行事
                .list-contents
                  - @star.dislike_events.each do |event|
                    %span.item #{event.name}
              %li
                %h5.mb-1 学校内で好きだった場所
                .list-contents
                  - @star.like_places.each do |place|
                    %span.item #{place.name}
              %li
                %h5.mb-1 学校内で苦手だった場所
                .list-contents
                  - @star.dislike_places.each do |place|
                    %span.item #{place.name}
              %li
                %h5.mb-1 学校について
                .list-contents
                  %span.item #{@star.preference_for_school_i18n}
    %a{"data-toggle" => "collapse", :href => "#collapse1", class: "seemore"}
      %h4.mb-1#trriger-text.seemore-text もっとみる

app/views/addictions/_search_by_negative.haml
#searchByNegativeModal.modal.fade{tabindex:"-1", role:"dialog", aria:{hidden:"true"}}
  .modal-dialog
    #modal_search_condition.modal-content
      .box_search_form
        %ul.search_tab_menu
          %li.tab_menu_item.is_current.w100p
            %a 嫌い・苦手なことから探す
        = search_form_for q, url:addictions_search_path, html:{id: 'search_condition_form'} do |f|
          .search_form_inner
            %table#search_condition_table.box_user_detail
              %tbody
                = render partial:"form_for_tags", locals: { category: "worry", row_name: "weak" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_event", junction_table: "stars_dislike_event" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_subject", junction_table: "stars_dislike_subject" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_place", junction_table: "stars_dislike_place" }
                = render partial:"check_boxes_for_enum", locals: { enum: "preference_for_school" }
                = render partial:"radio_buttons_for_enum", locals: { enum: "truancy_experience", f:f }
                %tr
                  %th 年齢
                  %td#search-age.search_age
                    =f.select :birthday_to_age_gteq, options_for_select((18..65).map{|n| ["#{n}", n]}),{include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                    %span 〜
                    =f.select :birthday_to_age_lteq, options_for_select((18..65).map{|n| ["#{n}", n]}), {include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "hometown" }
                = render partial:"check_boxes_for_enum", locals: { enum: "gender" }
                = render partial:"check_boxes_for_enum", locals: { enum: "sibling_position" }
                = render partial:"check_boxes_for_enum", locals: { enum: "family_env" }
                = render partial:"check_boxes_for_enum", locals: { enum: "economic_situation" }
            %ul.box_serach_button
              %li.serach_button_item.w20p
                %button#cancelSearchConditionBtn.modal-close.button_a.button_white_a{type:"button", data:{dismiss:"modal"}} キャンセル
              %li.serach_button_item.w40p
                %button#submitSearchConditionBtn.button_a.button_blue_a{type: "submit",remote:true} この条件で検索する

app/views/addictions/_search_by_positive.html.haml
#searchByPositiveModal.modal.fade{tabindex:"-1", role:"dialog", aria:{hidden:"true"}}
  .modal-dialog
    #modal_search_condition.modal-content
      .box_search_form
        %ul.search_tab_menu
          %li.tab_menu_item.is_current.w100p
            %a 好き・得意なことから探す
        = search_form_for q, url:addictions_search_path, html:{id: 'search_condition_form'} do |f|
          .search_form_inner
            %table#search_condition_table.box_user_detail
              %tbody
                = render partial:"form_for_tags", locals: { category: "speciality",row_name: "speciality" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_event", junction_table: "stars_like_event" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_subject", junction_table: "stars_like_subject" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_place", junction_table: "stars_like_place" }
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "school_club" }
                = render partial:"check_boxes_for_enum", locals: { enum: "preference_for_school" }
                %tr
                  %th 年齢
                  %td#search-age.search_age
                    =f.select :birthday_to_age_gteq, options_for_select((18..65).map{|n| ["#{n}", n]}),{include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                    %span 〜
                    =f.select :birthday_to_age_lteq, options_for_select((18..65).map{|n| ["#{n}", n]}), {include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "hometown" }
                = render partial:"check_boxes_for_enum", locals: { enum: "gender" }
                = render partial:"check_boxes_for_enum", locals: { enum: "sibling_position" }
                = render partial:"check_boxes_for_enum", locals: { enum: "family_env" }
                = render partial:"check_boxes_for_enum", locals: { enum: "economic_situation" }
            %ul.box_serach_button
              %li.serach_button_item.w20p
                %button#cancelSearchConditionBtn.modal-close.button_a.button_white_a{type:"button", data:{dismiss:"modal"}} キャンセル
              %li.serach_button_item.w40p
                %button#submitSearchConditionBtn.button_a.button_blue_a{type: "submit",remote:true} この条件で検索する

app/views/addictions/_search_by_worry.haml
#searchByWorryModal.modal.fade{tabindex:"-1", role:"dialog", aria:{hidden:"true"}}
  .modal-dialog
    #modal_search_condition.modal-content
      .box_search_form
        %ul.search_tab_menu
          %li.tab_menu_item.is_current.w100p
            %a 悩んでいることから探す
        = search_form_for q, url:addictions_search_path, html:{id: 'search_condition_form'} do |f|
          .search_form_inner
            %table#search_condition_table.box_user_detail
              %tbody
                = render partial:"form_for_tags", locals: { category: "worry", row_name: "worry" }
                = render partial:"check_boxes_for_enum", locals: { enum: "preference_for_school" }
                = render partial:"radio_buttons_for_enum", locals: { enum: "truancy_experience", f:f }
                %tr
                  %th 年齢
                  %td#search-age.search_age
                    =f.select :birthday_to_age_gteq, options_for_select((18..65).map{|n| ["#{n}", n]}),{include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                    %span 〜
                    =f.select :birthday_to_age_lteq, options_for_select((18..65).map{|n| ["#{n}", n]}), {include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "hometown" }
                = render partial:"check_boxes_for_enum", locals: { enum: "gender" }
                = render partial:"check_boxes_for_enum", locals: { enum: "sibling_position" }
                = render partial:"check_boxes_for_enum", locals: { enum: "family_env" }
                = render partial:"check_boxes_for_enum", locals: { enum: "economic_situation" }
            %ul.box_serach_button
              %li.serach_button_item.w20p
                %button#cancelSearchConditionBtn.modal-close.button_a.button_white_a{type:"button", data:{dismiss:"modal"}} キャンセル
              %li.serach_button_item.w40p
                %button#submitSearchConditionBtn.button_a.button_blue_a{type: "submit",remote:true} この条件で検索する

app/views/addictions/_search_form.html.haml
#user-modal.modal.fade{tabindex:"-1", role:"dialog", aria:{hidden:"true"}}
  .modal-dialog
    #modal_search_condition.modal-content
      .box_search_form
        %ul.search_tab_menu
          %li.tab_menu_item.is_current.w100p
            %a いろいろな項目から探す
        = search_form_for q, url:addictions_search_path, html:{id: 'search_condition_form'} do |f|
          .search_form_inner
            %table#search_condition_table.box_user_detail
              %tbody
                = render partial:"form_for_tags", locals: { category: "speciality",row_name: "speciality" }
                = render partial:"form_for_tags", locals: { category: "worry",row_name: "worry&weak" }
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "school_club" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_event", junction_table: "stars_like_event" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_event", junction_table: "stars_dislike_event" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_subject", junction_table: "stars_like_subject" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_subject", junction_table: "stars_dislike_subject" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_place", junction_table: "stars_like_place" }
                = render partial:"check_boxes_for_junction_tables", locals: { other_table: "school_place", junction_table: "stars_dislike_place" }
                = render partial:"check_boxes_for_enum", locals: { enum: "preference_for_school" }
                = render partial:"radio_buttons_for_enum", locals: { enum: "truancy_experience", f:f }
                %tr
                  %th 年齢
                  %td#search-age.search_age
                    =f.select :birthday_to_age_gteq, options_for_select((18..65).map{|n| ["#{n}", n]}),{include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                    %span 〜
                    =f.select :birthday_to_age_lteq, options_for_select((18..65).map{|n| ["#{n}", n]}), {include_blank:"こだわらない"}, {class:"hasCustomSelect search-select-age"}
                    %span.customSelect
                      %span.customSelectInner こだわらない
                = render partial:"select_boxes_for_other_tables", locals: { other_table: "hometown" }
                = render partial:"check_boxes_for_enum", locals: { enum: "gender" }
                = render partial:"check_boxes_for_enum", locals: { enum: "sibling_position" }
                = render partial:"check_boxes_for_enum", locals: { enum: "family_env" }
                = render partial:"check_boxes_for_enum", locals: { enum: "economic_situation" }
            %ul.box_serach_button
              %li.serach_button_item.w20p
                %button#cancelSearchConditionBtn.modal-close.button_a.button_white_a{type:"button", data:{dismiss:"modal"}} キャンセル
              %li.serach_button_item.w40p
                %button#submitSearchConditionBtn.button_a.button_blue_a{type: "submit",remote:true} この条件で検索する

app/views/addictions/_search_result.html.haml
.album.py-5.bg-light
  .container
    .row
      - @stars.each do |star|
        -if star.addiction
          .col-lg-4.col-sm-6
            .addiction-card.card.mx-1.my-1
              = link_to(addiction_path(star.addiction), class: 'profile__card') do
                .card-main-image.box-shadow
                  = image_tag(star.addiction.image)
                .card-body.p-3
                  .card-left.col-md-3.p-0
                    .rounded-circle.image-icon
                      = image_tag(star.avatar,class: "")
                  .card-right.col-md-9.p-0
                    .card-text.pl-2
                      %h4.addiction_title{style:"-webkit-box-orient: vertical;"}
                        = star.addiction.title
                      %p{style:"-webkit-box-orient: vertical;"}
                        = star.addiction.summary

app/views/addictions/_select_boxes_for_other_tables.html.haml
%tr#search_condition_item_row_residence.search_condition
  %th
    =translate_to_japanese(other_table)
  %td#residence.search_residence
    .form_block.nocustom
      =select_tag "q[#{other_table}_id_in][]", options_from_collection_for_select(other_table.classify.constantize.order("id"), :id, :name),{include_blank:"こだわらない",class:"select-residence-country hasCustomSelect"}
      %span.customSelect
        %span.customSelectInner こだわらない
    %a.button_f.button_white_a.add_form_btn 追加

app/views/addictions/index.html.haml
= render 'shared/header'
= render 'shared/head_jumbotron'
= render 'shared/search_head'
= render 'shared/middle_jumbotron'
.addictions
  .addictions__job
    .title
      %h2 仕事・活動
  = render partial: 'shared/addiction_card', locals: { addictions: @addictions_job }
  .addictions__hobby
    .title
      %h2 趣味・習い事
  = render partial: 'shared/addiction_card', locals: { addictions: @addictions_hobby }
  .addictions__browsed
    .title
      %h2 過去に見たもの
  = render partial: 'shared/addiction_card', locals: { addictions: @addictions_browsed }
= render partial: 'search_form', locals: { q: @q }
= render partial: 'search_by_positive', locals: { q: @q }
= render partial: 'search_by_negative', locals: { q: @q }
= render partial: 'search_by_worry', locals: { q: @q }

app/views/addictions/new.html.haml
/ %h1 New star

/ = render 'form'

/ = link_to 'Back', addictions_path

app/views/addictions/show.html.haml
= render 'shared/navbar'
.addiction-show
  .addiction-h_profile#profile
    %h1 プロフィール
  = render partial: 'profile_card', local: { star: @star }
  .addiction-show__body#summary
    .summary-title
      %i.fa.fa-lg.fa-star-o{"aria-hidden" => "true"}
      %i.fa.fa-2x.fa-star{"aria-hidden" => "true"}
      %i.fa.fa-lg.fa-star-o{"aria-hidden" => "true"}
      %h1 #{@addiction.title}
    .addiction-card
      .addiciton-img
        = image_tag("#{@addiction.image}")
      .addiction-content
        .addiction-text
          %p #{@addiction.summary}
      #addicted-points.addiction-content
        .addiction-h
          %h2 楽しいところ
        .addiction-text
          %p #{@addiction.addicted_points}
      #difficult-points.addiction-content
        .addiction-h
          %h2 大変なところ
        .addiction-text
          %p #{@addiction.difficult_points}
      #trigger.addiction-content
        .addiction-h
          %h2 ハマったきっかけ
        .addiction-text
          %p #{@addiction.trigger}
      #future-aim.addiction-content
        .addiction-h
          %h2 将来の目標
        .addiction-text
          %p #{@addiction.future_aim}
      #trying-things.addiction-content
        .addiction-h
          %h2 日々取り組んでいること
        .addiction-text
          %p #{@addiction.trying_things}
      #message.addiction-content
        .addiction-h
          %h2 メッセージ
        .addiction-text
          %p #{@addiction.message}
  .favorite-text.col-xs-9
    %p 一番上の お気に入り からいつでも見られるよ！
  .favorite.col-xs-3
    - if user_signed_in?
      = render partial: 'likes/like', locals: {addiction: @addiction}
    - else
      = link_to like_path(@addiction.id), method: :post do
        .favorite-btn{:id => "like-button-#{@addiction.id}"}
          .favorite-btn__star
            %p ★